experiment:
  imaging:
    binning: 4x4
    fiddle: 1.0
    fluor_to_frames:
      DAPI: 0
      GFP: 0
      RFP: 0
    fluors:
    - RFP
    - GFP
    - DAPI
    group_control_label: some-dna1
    group_labels:
    - some-dna4
    - some-dna1
    - some-dna3
    - some-dna2
    group_labels_to_wells:
      some-dna1:
      - A01
      some-dna2:
      - A02
      some-dna3:
      - A03
      some-dna4:
      - A04
    magnification: 20
    make_stacks: false
    microscope: flo2
    montage_num: '4'
    primary_channel: RFP
    tile_overlap: 10
    wells:
      A01:
        dna1: some-dna1
        dna2: NA
        drug1: NA
        drug2: NA
        label: some-dna1
      A02:
        dna1: some-dna2
        dna2: NA
        drug1: NA
        drug2: NA
        label: some-dna2
      A03:
        dna1: some-dna3
        dna2: NA
        drug1: NA
        drug2: NA
        label: some-dna3
      A04:
        dna1: some-dna4
        dna2: NA
        drug1: NA
        drug2: NA
        label: some-dna4
      A05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      A12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      B12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      C12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      D12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      E12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      F12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      G12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H01:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H02:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H03:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H04:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H05:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H06:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H07:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H08:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H09:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H10:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H11:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
      H12:
        dna1: NA
        dna2: NA
        drug1: NA
        drug2: NA
        label: ''
  name: ExampleExperiment
  setup:
    plate: 96w
  text_notification: 5551234567@vtext.com
  time_data:
    hours:
    - '24'
    - '47'
    - '71'
    - '107'
    - '131'
    - '143'
    - '167'
    - '191'
    - '215'
    - '239'
    timepoint_num: 10
    timepoints:
    - 1 24 8/29/2018
    - 2 47 8/30/2018
    - 3 71 8/31/2018
    - 4 107 9/1/2018
    - 5 131 9/2/2018
    - 6 143 9/3/2018
    - 7 167 9/4/2018
    - 8 191 9/5/2018
    - 9 215 9/6/2018
    - 10 239 9/7/2018
    transfection:
      day: 8/28/2018
      time: 9:00 AM
  well-data:
    well-to-cell-type:
      A01: cortical
      A02: cortical
      A03: cortical
      A04: cortical
      A05: cortical
      A06: cortical
      A07: cortical
      A08: cortical
      A09: cortical
      A10: cortical
      A11: cortical
      A12: cortical
      B01: cortical
      B02: cortical
      B03: cortical
      B04: cortical
      B05: cortical
      B06: cortical
      B07: cortical
      B08: cortical
      B09: cortical
      B10: cortical
      B11: cortical
      B12: cortical
      C01: cortical
      C02: cortical
      C03: cortical
      C04: cortical
      C05: cortical
      C06: cortical
      C07: cortical
      C08: cortical
      C09: cortical
      C10: cortical
      C11: cortical
      C12: cortical
      D01: cortical
      D02: cortical
      D03: cortical
      D04: cortical
      D05: cortical
      D06: cortical
      D07: cortical
      D08: cortical
      D09: cortical
      D10: cortical
      D11: cortical
      D12: cortical
      E01: cortical
      E02: cortical
      E03: cortical
      E04: cortical
      E05: cortical
      E06: cortical
      E07: cortical
      E08: cortical
      E09: cortical
      E10: cortical
      E11: cortical
      E12: cortical
      F01: cortical
      F02: cortical
      F03: cortical
      F04: cortical
      F05: cortical
      F06: cortical
      F07: cortical
      F08: cortical
      F09: cortical
      F10: cortical
      F11: cortical
      F12: cortical
      G01: cortical
      G02: cortical
      G03: cortical
      G04: cortical
      G05: cortical
      G06: cortical
      G07: cortical
      G08: cortical
      G09: cortical
      G10: cortical
      G11: cortical
      G12: cortical
      H01: cortical
      H02: cortical
      H03: cortical
      H04: cortical
      H05: cortical
      H06: cortical
      H07: cortical
      H08: cortical
      H09: cortical
      H10: cortical
      H11: cortical
      H12: cortical
    well-to-drug:
      A01: NA
      A02: NA
      A03: NA
      A04: NA
      A05: NA
      A06: NA
      A07: NA
      A08: NA
      A09: NA
      A10: NA
      A11: NA
      A12: NA
      B01: NA
      B02: NA
      B03: NA
      B04: NA
      B05: NA
      B06: NA
      B07: NA
      B08: NA
      B09: NA
      B10: NA
      B11: NA
      B12: NA
      C01: NA
      C02: NA
      C03: NA
      C04: NA
      C05: NA
      C06: NA
      C07: NA
      C08: NA
      C09: NA
      C10: NA
      C11: NA
      C12: NA
      D01: NA
      D02: NA
      D03: NA
      D04: NA
      D05: NA
      D06: NA
      D07: NA
      D08: NA
      D09: NA
      D10: NA
      D11: NA
      D12: NA
      E01: NA
      E02: NA
      E03: NA
      E04: NA
      E05: NA
      E06: NA
      E07: NA
      E08: NA
      E09: NA
      E10: NA
      E11: NA
      E12: NA
      F01: NA
      F02: NA
      F03: NA
      F04: NA
      F05: NA
      F06: NA
      F07: NA
      F08: NA
      F09: NA
      F10: NA
      F11: NA
      F12: NA
      G01: NA
      G02: NA
      G03: NA
      G04: NA
      G05: NA
      G06: NA
      G07: NA
      G08: NA
      G09: NA
      G10: NA
      G11: NA
      G12: NA
      H01: NA
      H02: NA
      H03: NA
      H04: NA
      H05: NA
      H06: NA
      H07: NA
      H08: NA
      H09: NA
      H10: NA
      H11: NA
      H12: NA
    well-to-drug-conc:
      A01: NA
      A02: NA
      A03: NA
      A04: NA
      A05: NA
      A06: NA
      A07: NA
      A08: NA
      A09: NA
      A10: NA
      A11: NA
      A12: NA
      B01: NA
      B02: NA
      B03: NA
      B04: NA
      B05: NA
      B06: NA
      B07: NA
      B08: NA
      B09: NA
      B10: NA
      B11: NA
      B12: NA
      C01: NA
      C02: NA
      C03: NA
      C04: NA
      C05: NA
      C06: NA
      C07: NA
      C08: NA
      C09: NA
      C10: NA
      C11: NA
      C12: NA
      D01: NA
      D02: NA
      D03: NA
      D04: NA
      D05: NA
      D06: NA
      D07: NA
      D08: NA
      D09: NA
      D10: NA
      D11: NA
      D12: NA
      E01: NA
      E02: NA
      E03: NA
      E04: NA
      E05: NA
      E06: NA
      E07: NA
      E08: NA
      E09: NA
      E10: NA
      E11: NA
      E12: NA
      F01: NA
      F02: NA
      F03: NA
      F04: NA
      F05: NA
      F06: NA
      F07: NA
      F08: NA
      F09: NA
      F10: NA
      F11: NA
      F12: NA
      G01: NA
      G02: NA
      G03: NA
      G04: NA
      G05: NA
      G06: NA
      G07: NA
      G08: NA
      G09: NA
      G10: NA
      G11: NA
      G12: NA
      H01: NA
      H02: NA
      H03: NA
      H04: NA
      H05: NA
      H06: NA
      H07: NA
      H08: NA
      H09: NA
      H10: NA
      H11: NA
      H12: NA
    well-to-drug-conc-units:
      A01: NA
      A02: NA
      A03: NA
      A04: NA
      A05: NA
      A06: NA
      A07: NA
      A08: NA
      A09: NA
      A10: NA
      A11: NA
      A12: NA
      B01: NA
      B02: NA
      B03: NA
      B04: NA
      B05: NA
      B06: NA
      B07: NA
      B08: NA
      B09: NA
      B10: NA
      B11: NA
      B12: NA
      C01: NA
      C02: NA
      C03: NA
      C04: NA
      C05: NA
      C06: NA
      C07: NA
      C08: NA
      C09: NA
      C10: NA
      C11: NA
      C12: NA
      D01: NA
      D02: NA
      D03: NA
      D04: NA
      D05: NA
      D06: NA
      D07: NA
      D08: NA
      D09: NA
      D10: NA
      D11: NA
      D12: NA
      E01: NA
      E02: NA
      E03: NA
      E04: NA
      E05: NA
      E06: NA
      E07: NA
      E08: NA
      E09: NA
      E10: NA
      E11: NA
      E12: NA
      F01: NA
      F02: NA
      F03: NA
      F04: NA
      F05: NA
      F06: NA
      F07: NA
      F08: NA
      F09: NA
      F10: NA
      F11: NA
      F12: NA
      G01: NA
      G02: NA
      G03: NA
      G04: NA
      G05: NA
      G06: NA
      G07: NA
      G08: NA
      G09: NA
      G10: NA
      G11: NA
      G12: NA
      H01: NA
      H02: NA
      H03: NA
      H04: NA
      H05: NA
      H06: NA
      H07: NA
      H08: NA
      H09: NA
      H10: NA
      H11: NA
      H12: NA
